### ISSUE TITLE
fix yarn check v1.3.2 

### ISSUE THREAD

**Issue by airqz** [highkix/ratptimer#3]
yarn check v1.3.2
warning "chokidar#fsevents#node-pre-gyp@^0.6.39" could be deduped from "0.6.39" to "node-pre-gyp@0.6.39"

**Comment by highkix** [comment]
hi airqz ;)

You can try `npm install -g node-gyp` then retry to run `yarn check` or `yarn check --integrity`.
It works for me.

**Comment by airqz** [comment]
nothing change for me

**Comment by highkix** [comment]
Related to https://github.com/yarnpkg/yarn/issues/2287 and https://github.com/strongloop/fsevents/issues/157
